---
title: Wittle Website
timezone: UTC
collections:
  media:
    title: Media
    output: true
  organization:
    title: Organization
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  stories:
    title: Stories
    output: true
  symptoms:
    title: Symptoms
    output: true
  treatment:
    title: Therapy
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
    - scope:
        path: ''
        type: media
      values:
        shortDescription:
        relationDepression:
        linkPlay:
        linkClip:
        mediaType: 
        platform: 
        image: 
        subject:
        Symptoms: []
        Therapy:[]
