---
title: Wittle Website
timezone: UTC
collections:
  organization:
    title: Organization
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  stories:
    title: Stories
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    isInNav: 
- scope:
    path: ''
    type: stories
  values:
    description: 
    link:
      text: 
      url: 
    image: 
- scope:
    path: ''
    type: people
  values:
    bio: 
    social:
      link: 
      site: 
