---
title: Wittle Website
timezone: UTC
collections:
  media:
    title: Media
    output: true
  organization:
    title: Organization
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
    - scope:
        path: ''
        type: media
      values:
        link:
        mediaType: 
        platform: 
        image: 
        subject:
        DepressionSymptoms: []
